-- Active: 1674041361256@@127.0.0.1@5432@myproject
CREATE OR REPLACE PROCEDURE FN()
LANGUAGE PLPGSQL AS
$$
    BEGIN 
        INSERT INTO CARS(NAME) VALUES ('X');
        ROLLBACK;
        INSERT INTO CARS(NAME) VALUES ('Y');
        COMMIT;
        INSERT INTO CARS(NAME) VALUES ('Z');
        INSERT INTO CARS(NAME) VALUES ('z');
    END;
;
$$;

-- TRANSACTION
BEGIN WORK
    SELECT 1;
END;