-- Active: 1674041361256@@127.0.0.1@5432@myproject
-- SELECT CURRENT USER
SELECT CURRENT_USER;

SELECT $$

    MEN OG'ALARIM BILAN O'ZBEKISTONDAGI O'RMONDA G'OZ VA O'RDAK OVLASHNI O'RGANYAPMIZ

$$;

SELECT $MESSAGE$ HELLO WORLD $MESSAGE$;

SELECT $EXP$ 2+2 $EXP$;

SELECT $EXP2X$ 2+2 $EXP2X$ AS X; 

-- PLPGSQL
-- SQL

-- 
DO
$$
    BEGIN
        RAISE INFO '% %', 20, 'SHEROZBEK';
    END;
$$
;

DO $$

    DECLARE
        NAME CONSTANT VARCHAR := 'SHEROZBEK';
        AGE INT :=20;

    BEGIN

        AGE := AGE +1;


        RAISE INFO '% %', NAME, AGE;
    END;

$$

CREATE TABLE COMMENTS (
    COMMENT_ID SERIAL NOT NULL PRIMARY KEY,
    CONTENT CHARACTER VARYING(128) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MOVIE_ID INT NOT NULL REFERENCES MOVIES(MOVIE_ID),
    USER_ID INT NOT NULL REFERENCES USER(USER_ID),
);

COMMENT ON TABLE COMMENTS IS 'FILM UCHUN IZOHLAR';

INSERT INTO COMMENTS (CONTENT, MOVIE_ID, USER_ID) VALUES ('DAVOMINI QACHON CHIQARASIZLAR', 1, 2);

INSERT INTO COMMENTS (CONTENT, MOVIE_ID, USER_ID) VALUES ('YAXSHI KINO EKAN', 1, 3);

INSERT INTO COMMENTS (CONTENT, MOVIE_ID, USER_ID) VALUES ('MAN 1', 2, 1     );



SELECT
    C.MOVIE_ID,
    COUNT(C.MOVIE_ID) AS COMMONTES,
    M.NAME
FROM
    COMMENTS AS C
JOIN
    MOVIES AS M ON M.MOVIE_ID = C. MOVIE_ID
GROUP BY
    C.MOVIE_ID, M.NAME
ORDER BY COMMENTS DESC
;



SELECT
    C.MOVIE_ID,
    COUNT(C.MOVIE_ID) ASS COMMENTS
FROM
    COMMENTS AS C
JOIN
    MOVIES AS M ON M.MOVIE_ID = C.MOVIE_ID
GROUP BY
    C.MOVIE_ID
;

CREATE FUNCTION GREETING() RETURNS  INT LANGUAGE PLPGSQL AS
$$
    BEGIN

        RAISE INFO 'HELLO WORLD';
        RETURNS 1;

    END;
$$;

CREATE OR REPLACE FUNCTION GREETING(X INT, Y INT) RETURNS INT LANGUAGE PLPGSQL
    AS
$$
    BEGIN

        SELECT PG_SLEEP(5);
        RETURN X +Y;
    END;
$$;

CREATE OR REPLACE FUNCTION SOME_USER (ID_INT) RETURNS TABLE (FULLNAME CHARACTER VARYING) LANGUAGE PLPGSQL AS $$

    DECLARE
        U_ID INT := ID;

    BEGIN
        RETURN QUERY (SELECT NAME FROM USERS WHERE USER_ID = ID);
    END;
$$;