-- Active: 1674041361256@@127.0.0.1@5432@myproject
-- A    1
-- B    2
-- C    3
-- D    4
-- E    5
-- F    6
-- G    7
-- H    8

CREATE TABLE LETTERS (
    ID  SERIAL NOT NULL PRIMARY KEY,
    L VARCHAR(1) NOT NULL
);

INSERT INTO LETTERS(L) VALUES ('A'), ('B'), ('C'), ('D'), ('E'), ('F'), ('G'), ('H');

SELECT * FROM LETTERS AS L1 WHERE (

    SELECT COUNT(L2.ID) % 2 !=0
    FROM LETTERS AS L2
    WHERE L2.ID < L1.ID
);

SELECT
    *
FROM
    LETTERS
WHERE
    2 > 1 AND 3 > 1
;

CREATE TABLE CATIGORIES (
    CATIGORY_ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(24) NOT NULL
);

CREATE TABLE TABLES (
    TABLE_ID SERIAL NOT NULL PRIMARY KEY,
    NUMBER INT2 NOT NULL
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    PRICE DECIMAL(16, 2) NOT NULL,
    CATEGORY_ID INT NOT NULL REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID SERIAL NOT NULL PRIMARY KEY,
    TABLE_ID INT NOT NULL REFERENCES TABLES(TABLE_ID),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID SERIAL NOT NULL PRIMARY KEY,
    ORDER_ID INT NOT NULL REFERENCES ORDERS(ORDER_ID),
    PRODUCT_ID INT NOT NULL REFERENCES PRODUCTS(PRODUCT_ID)
);

