-- Active: 1674041361256@@127.0.0.1@5432@myproject
INSERT INTO COMPONENTS (NAME) VALUES
('KARTOSHKA'), ('SABZI'), ('GURUCH'), ('PIYOZ'), ('BODRING');

INSERT INTO CATEGORIES (NAME) VALUES
('MILLIY TAOMLAR'), ('YEVROPA TAOMLARI'), ('ICHIMLIKLAR');

INSERT INTO CATEGORIES (NAME) VALUES
('QUYUQ'), ('SUYUQ'), ('SALAT'), ('SALQIN ICHIMLIKLAR');

INSERT INTO CATEGORIES (NAME) VALUES
('QUYUQ'), ('SUYUQ'), ('SALAT'), ('SALQIN ICHIMLIKLAR');

CREATE TABLE TYPE_REGISTER(
    TYPE_REGISTER_ID SERIAL NOT NULL PRIMARY KEY,
    CATEGORY_ID INT NOT NULL REFERENCES CATEGORIES(CATEGORY_ID),
    TYPE_ID INT NOT NULL REFERENCES TYPES(TYPE_ID)
);

INSERT INTO TYPE_REGISTER (CATEGORY_ID, TYPE_ID) VALUES
(1, 1), (1, 2), (1, 3),
(2, 3),
(3, 4),
(3, 5),
(3, 6)
;

INSERT INTO PRODUCTS (NAME, PRICE, TYPE_REGISTER_ID) VALUES
 ('OSH', 16000, 1), ('MASTAVA', 12000, 2),
('OLIVIE', 18000, 4),
('COCA-COLA 250ML', 5000, 5)
('MOXITO', 11000, 5),
('CHOY', 3000, 6),
('LIMON CHOY', 5000, 6),
('RED-BULL 500ML', 28000, 7)
;


 