-- Active: 1674041361256@@127.0.0.1@5432@myproject
INSERT INTO CATEGORIES(NAME) VALUES ('MILLIY TAOMLAR'), ('YEVROPA TAOMLARI'), ('TURK TAOMLAR');

INSERT INTO TYPES (NAME) VALUES ('QUYUQ OVQATLAR'), ('SUYUQ OVQATLAR'), ('ICHIMLIKLAE'), ('SHIRINLIKLAR'), ('SALATLAR')
;
