-- Active: 1674041361256@@127.0.0.1@5432@myproject
CREATE TABLE USERS (
    USER_ID NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING(32) NOT NULL
);

CREATE TABLE MOVIES (
    MOVIE_ID SERIAL NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING(128) NOT NULL 
);

CREATE TABLE FOVOURITES (
    FAVOURITE_ID SERIAL NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES USERS (USER_ID),
    MOVIE_ID INT NOT NULL REFERENCES MOVIES (MOVIE_ID)
);

COMMENT ON TABLE USERS IS 'FOYDALANUVCHILAR';
COMMENT ON TABLE MOVIES IS 'FILMLAR';
COMMENT ON TABLE FAVOURITES IS 'SEVIMLI FILMLAR';

INSERT INTO USERS (NAME) VALUES ('HUSNIDDIN') ('FARRUX') ('ABDULLOH');
INSERT INTO MOVIES (NAME) VALUES ('QOG''OZ BINO'), ('GARRI POTR'), ('ABDULLAJON');

INSERT INTO FAVOURITES(USER_ID, MOVIE_ID) VALUES (1, 2), (2,1), (2,2), (3,2);

SELECT
    F.FAVOURITE_ID,
    F.USER_ID,  
    M.NAME AS MOVIE 
FROM FAVOURITES AS F
NATURAL JOIN MOVIES AS M
;
