-- Active: 1674041361256@@127.0.0.1@5432@myproject

create table authors (
    id serial not null primary key,
    firstname varchar(20) not null,
    lastnmae varchar(20) null   
);

create table books (
    book_id serial not null primary key,
    name varchar(20) not null,
    price decimal(20) null   
);

insert into authors (firstname) values ('Khamidov');

insert into books (name) values ('Vaqt');

create table users (
    user_id int generated always as identity primary key,
    usernmae character varying(20) not null,
    password character varying(60) not null,
    firstname character varying(20) not null,
    lastnmae character varying (20) null,
    birth date null
    gender int2,
    is_active bool default true
);

create table contacts (
    contact_id int generated by default as identity primary key,
    type int2 not null,
    content character varying(64),
    user_id int not null references users (user_id)
);

create table products(
    product_id serial not null primary key,
    name varchar(32) not null,
);

create table tables(
    table_id serial not null primary key,
    number smallint not null
);

create table orders(
    order_id serial not null primary key,
    table_id id int not null references tables (table_id),
    product_id int not null references products (product_id)
);

insert into products (name) values ('Osh'), ('Qozon kabob') ('Lagmon');
insert into tables (number) values (1), (2), (3), (4);

insert into users (username, password, firstname, lastname, birth, gender)
    values ('muhammad', 'muhammad1', 'Muhammad', 'Najimov', '01-01-1994', 2)
    ;

insert into users (username, password, firstname, lastname, birth, gender)
    values ('sherozbek', 'sherozbek1', 'Sherozbek', 'Khamidov', '26-08-2003', 2)
    ;

insert into contacts(type, content, whos_id) values (1, '998949949994', 2);
insert into contacts(type, content, whos_id) values (1, '998934756669', 1);
insert into contacts(type, content, whos_id) values (2, 'sherozbekkhamidov@gmail.com', 2);

create table categories (
    category_id serial not null primary key,
    name varchar (64)
);

create table authors(
    author_id serial not null primary key,
    name varchar(64)
);

create table books(
    book_id serial not null primary key,
    price decimal(5, 2),
    name varchar(64),
    category_id int not null references categories (categoty_id)
);

create table orders(
    order_id serial not null primary key,
    book_idint not null references books (book_id),
    created at timestamp  default current timestamp,
    author_id int not null references authors (authors_id)
);

create table orders(
    order_id serial not null primary key,
    book_id int not null references books (book_id);
    created_at timestamp default current_timestamp
);

insert into categories (name) values ('Software Engeneering') ('Electrical Engeneering');

insert into authors (name) values ('Ken Thomson');
insert into authors (name) values ('Jonathan Ive');

insert into books (price, name, category_id, author_id) values (65, 'UI Experience', 1,2 )
;

insert into books (price, name,category_id, author_id) values (80, 'The Defenetive Guide Golang', 1,1);

insert into books (price, name,category_id, author_id) values (80, 'TMicrocontroller basics', 2,1);

create table users(
    user_id serial not null primary key,
    name varchar (48) not null
);

create extension pgcrypto;
create table cash(
    cash_id serial not null primary key,
    amount decimal(16, 2) not null,
    summary varchar(32) null,
    created_at timestamp default current_timestamp,
    user_id int not null references users (user_id)
);

create table cost(
    cost_id serial not null primary key,
    amount decimal(16, 2) not null,
    summary varchar(32) null,
    created_at timestamp default current_timestamp,
    user_id int not null references users (user_id)
);

--mock data
 

--  inseert into users();


--  insert into users (name, username, password) values ('Farrux Ismoilov', 'farrux', crypt('farrux1', geb_salt('bf')));

--  insert into users (name, username, password) values ('Husan Musa', 'husan', crypt('husan1', geb_salt('bf')));

insert into cash(amount, summary, user_id) values (100000, null, 1);
insert into cash(amount, summary, user_id) values (200000, Avans, 2);

insert into cash(amount, summary, user_id) values (5000, Coca-cola, 2);
insert into cash(amount, summary, user_id) values (30000, Abed, 2);
insert into cash(amount, summary, user_id) values (10000, null, 2);

insert into cash(amount, summary, user_id) values (100000, Abed, 1);

select
    sum(cash.amount) as cash,
    (select sum(amount)from cost where user_id = 2) as cost,

    sum(cash.amount) - (select sum(amount) from cost where user_id = 2) as select

from cash
where cash.user_id=2
;

create table teams (
    team_id serial not null primary key,
    name varchar(64) not null,
    group_id int not null references group(group_id) 
);

create table matches (
    match_id serial not null primary key.
    date date null,
);

CREATE TABLE PLAYERS(
    PLAYER_ID SERIAL NOT NULL,
    MATCH_ID INT NOT NULL REFERENCES MATCHES (MATCH_ID),
    TEAM_ID INT NOT NULL REFERENCES TEAMS (TEAM_ID),
    GOALS SMALLINT DEFAULT 0
);
