-- Active: 1674041361256@@127.0.0.1@5432@myproject
SELECT
    G.LABEL AS GROUP,
    C.NAME AS CLUB
FROM TEAMS AS T
NATURAL JOIN GROUPS AS G
NATURAL JOIN CLUBS AS C
WHERE G.TOURNAMENT_ID = 1
ORDER BY G.LABEL
;


SELECT
    G.LABEL AS GROUP,
    ARRAY_AGG(C.NAME) AS CLUB
FROM TEAMS AS T
NATURAL JOIN GROUPS AS G
NATURAL JOIN CLUBS AS C
WHERE G.TOURNAMENT_ID = 1
GROUP BY G.GROUP_ID 
ORDER BY G.LABEL
;

SELECT
    G.LABEL AS GROUP,
    C.NAME AS CLUB,
    M.DATE AS MATCH_DAY
FROM PLAYERS AS P
NATURAL JOIN TEAMS AS T
JOIN GROUPS AS G ON G.GROUP_ID = T.GROUP_ID
JOIN CLUBS AS C ON C.CLUB_ID = T.CLUB_ID
NATURAL JOIN MATCHES AS M
WHERE M.TOURNMENT_ID = 1 AND M.MATCH_ID = 1
;
