-- Active: 1674041361256@@127.0.0.1@5432@myproject
SELECT 
    CASE 2
        WHEN 2 THEN 'TWO'
        WHEN 3 THEN 'THREE'
        ELSE 'NULL'
    END;

SELECT CASE WHEN (SELECT COUNT(*) FROM X) > 100 THEN 'OK' ELSE NULL END;

CREATE TYPE SUMMA AS VARCHAR(20);

CREATE TYPE GENDER AS ENUM('MALE', 'FEMALE');
CREATE TYPE COLORS AS ENUM('BLACK', 'RED', 'BROWN');

CREATE TYPE XTABLE AS (
    ID INT,
    NAME VARCHAR
);

CREATE DOMAIN VALID_NAME AS VARCHAR(20) NOT NULL CHECK(VALUE !~ '/S');

CREATE TABLE ACCOUNTS (
    ID SERIAL NOT NULL PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    GENDER GENDER,
    BALANCE DECIMAL(16, 2) NULL 
);

INSERT INTO ACCOUNTS(FNAME, LNAME, GENDER, TEST_C) VALUES ('MUHAMMAD', 'NAJIMOV', 'MALE', (1, 'HELLO'));


CREATE FUNCTION F1()
RETURNS VOID
LANGUAGE PLPGSQL AS
$$
    BEGIN

    END;
$$;

CREATE OR REPLACE FUNCTION F1()
RETURNS TABLE (LIKE PRODUCTS)
LANGUAGE PLPGSQL AS
$$
    BEGIN
        RETURN QUERY SELECT * FROM PRODUCTS;
    END;
$$; 

CREATE TABLE ELEMENTS (
    ID SERIAL NOT NULL PRIMARY KEY,
    DATE CHAR(1)
);

CREATE TABLE OBJECTS (
     ID SERIAL NOT NULL PRIMARY KEY,
    DATE CHAR(1)
);

INSERT INTO  ELEMENTS(DATA) VALUES ('A'), ('B'), ('C');
INSERT INTO  OBJECTS(DATA) VALUES ('A'), ('B'), ('C'), ('D'), ('E');

SELECT * FROM OBJECTS
UNION ALL
SELECT * FROM ELEMENTS;

