-- Active: 1674041361256@@127.0.0.1@5432@myproject
-- BUGUNGI BUYURTMALAR
-- ENG KOP BUYURTMA QILINGAN TOVARLAR
-- BIROR TOVAR BILAN ENG KOP ISHTIROK ETGAN BOSHQA TOVAR
-- ENG FOAL BUYURTMALAR KUNINI ANIQLASH
-- CHO'CHEGA QARAB OVQAT BUYURTMA QILISH

SELECT
    O.*
FROM ORDERS AS O
WHERE CREATED_AT :: DATE = CURRENT_DATE AND O.CLOSED_AT IS NOT NULL
;

SELECT EXTRACT(YEAR FROM NOW());

SELECT
    P.NAME,
    SUM(D.QUANTITY) QUANTITY
FROM ORDER_DETAILS AS D
NATURAL JOIN PRODUCTS AS P
GROUP BY D.PRODUCT_ID, P.NAME
ORDER BY QUANTITY DESC
LIMIT 1
;

CREATE TABLE TABLE_A (
    A_ID SERIAL NOT NULL PRIMARY KEY,
    A_CONTENT VARCHAR(1)
);

CREATE TABLE TABLE_B (
    B_ID SERIAL NOT NULL PRIMARY KEY,
    B_CONTENT VARCHAR(1),
    A_ID INT NOT NULL REFERENCES TABLE_A(A_ID)
);

INSERT INTO TABLE_A(A_CONTENT) VALUES (1), (2), (3);
INSERT INTO TABLE_B(B_CONTENT, A_ID) VALUES ('A', 1), ('B', 1), ('C', 2);

SELECT
    A.*
FROM TABLE_A AS A
LEFT JOIN TABLE_B AS B ON A.A_ID = B.A_ID
;

SELECT
    A.*
FROM TABLE_A AS A
LEFT JOIN TABLE_B AS B ON A.A_ID = B.A_ID
;

CREATE TABLE zoo_1 (
    id INT PRIMARY KEY,
    animal VARCHAR (100) NOT NULL
);


CREATE TABLE zoo_2 (
    id INT PRIMARY KEY,
    animal VARCHAR (100) NOT NULL
);

INSERT INTO zoo_1(id, animal)
VALUES
    (1, 'Lion'),
    (2, 'Tiger'),
    (3, 'Wolf'),
    (4, 'Fox');
 
 INSERT INTO zoo_2(id, animal)
VALUES
    (1, 'Tiger'),
    (2, 'Lion'),
    (3, 'Rhino'),
    (4, 'Panther');

SELECT
    zoo_1.id id_a,
    zoo_1.animal animal_a,
    zoo_2.id id_b,
    zoo_2.animal animal_b
FROM
    zoo_1 
INNER JOIN zoo_2 ON zoo_1.animal = zoo_2.animal;

CREATE TABLE CARS (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(24) NOT NULL,
    COLORS VARCHAR[]
);

INSERT INTO CARS (NAME, COLORS) VALUES ('PHANTOM', '{"BLACK", "WHITE"}');
INSERT INTO CARS (NAME, COLORS) VALUES ('FERRARI', ARRAY['RED', 'BLACK']);
INSERT INTO CARS (NAME, COLORS) VALUES ('DAMAS', ARRAY['WHITE', 'BLACK']);


SELECT
    NAME,
    COLORS[2]
FROM
    CARS
WHERE
    COLORS[1] = 'BLACK'
;


SELECT ARRAY_APPEND(ARRAY['A', 'B'], 'C');
SELECT ARRAY_PREPEND('C', ARRAY['A', 'B']);